layout_spectrum: 0.37096535530872643
typography_spectrum: 0.4180846828967333
color:
  brandStrength: 0.004434158559888601
  lightness: 0.8986572085414082
  saturation: 0.680958179756999
  rhythmicContrast: 0.8474827297031879
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#737373'
    - '#3D3D3D'
    - '#D0D0D0'
name: nativalien
navigation:
  - name: C.KING
    url: www.ckingdom.com
    type: external
  - name: Portfolio
    url: www.nativalien.com
    type: external
title: Alien Artifaq
description: Designed by natives
