typography_spectrum: 0.006011663703247905
color:
  brandStrength: 0.18790933582931757
  lightness: 0.8830895889550447
  saturation: 0.11315449164249003
  rhythmicContrast: 0.22785785840824246
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#737373'
    - '#3D3D3D'
    - '#D0D0D0'
layout_spectrum: 0.9539050327148288
name: nativalien
navigation:
  - name: C.KING
    url: www.ckingdom.com
    type: external
  - name: Portfolio
    url: www.nativalien.com
    type: external
title: Alien Artifaq
description: Designed by natives
