typography_spectrum: 0.4479308989830315
color:
  brandStrength: 0.2273466440383345
  lightness: 0.07603172771632671
  saturation: 0.6902973495889455
  rhythmicContrast: 0.9921282683499157
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
layout_spectrum: 0.7202084604650736
name: nativalien
navigation:
  - name: C.KING
    url: www.ckingdom.com
    type: external
  - name: Portfolio
    url: www.nativalien.com
    type: external
title: Alien Artifaq
description: Designed by natives
